Dev new web
WeBankFinTech/DataSphereStudio pull request #457
Opened 2021-12-16 06:28 UTC by det101

2021-12-23 02:57 UTC, RiESAEX requested changes
我注意到有许多文件只有权限变化 可以剔除他们吗

2021-12-23 03:03 UTC, det101 commented
> 



> 我注意到有许多文件只有权限变化 可以剔除他们吗
可以的，可以举几个文件的例子吗？

2021-12-23 03:27 UTC, RiESAEX commented
![image](https://user-images.githubusercontent.com/89718456/147181951-d520035a-9d04-4402-baa6-231635d113d0.png)
基本上是/web/下面的
```git diff -v pr/457 origin/dev-1.0.1 -p |grep -E '^(diff|old mode|new mode)'```

2021-12-24 06:18 UTC, det101 commented
> ![image](https://user-images.githubusercontent.com/89718456/147181951-d520035a-9d04-4402-baa6-231635d113d0.png) 基本上是/web/下面的 `git diff pr/457 origin/dev-1.0.1 -p | grep -E '^(diff|old mode|new mode)'`

已经修改

2021-12-24 06:18 UTC, det101 commented on web/install.sh
> +>>>>>>> b5c29e41490d1200fbd6b32f407ea018def62aec
已经删除

2021-12-24 06:18 UTC, det101 commented on web/install.sh
> +>>>>>>> b5c29e41490d1200fbd6b32f407ea018def62aec
已处理

2021-12-24 06:18 UTC, det101 commented on web/yarn-error.log
> +Arguments:
已删除

2021-12-24 12:19 UTC, RiESAEX reviewed
web/src/apps/dataService/assets/images/dssLogo5_1.png
web/src/apps/linkis/assets/images/dssLogo5.png
我注意到有好几个这个图 是不是可以只留一个

2021-12-24 12:19 UTC, RiESAEX commented on web/upload.201.sh
> +scp -r ./dist/dist root@172.24.2.230:/usr/local/anlexander/web
这个文件看起来没用？

2021-12-24 12:19 UTC, RiESAEX commented on web/server.Dockerfile
> +RUN npm install --registry http://10.37.31.58:4873/
这个npm源和docker源都是内网服务吧

2021-12-27 06:35 UTC, det101 commented on web/src/apps/dataGovernance/service/db/node.js
> +      if (isArray(key)) {
这个原来就是这样的，这几个模块可以单独拆出来，是微众的设计

2021-12-27 06:37 UTC, det101 commented on web/server.Dockerfile
> +RUN npm install --registry http://10.37.31.58:4873/
已经改

2021-12-27 11:38 UTC, RiESAEX commented on web/server.Dockerfile
> +RUN npm install --registry http://10.37.31.58:4873/
我这看没变啊？

2021-12-27 11:56 UTC, det101 commented on web/src/apps/scriptis/assets/images/flink.svg
>  <?xml version="1.0" encoding="UTF-8" standalone="no"?>
已处理

2021-12-27 11:56 UTC, det101 commented on web/upload.201.sh
> +scp -r ./dist/dist root@172.24.2.230:/usr/local/anlexander/web
已经删除

2021-12-27 12:04 UTC, det101 commented on web/src/apps/linkis/router.js
> +export default [
这块社区已经迁移到linkis下

2021-12-28 06:54 UTC, RiESAEX commented
@det101 

可以麻烦把鲁班/鲁蛋相关的文字和图片替换/删除掉吗
比如dss/assets/images/下面有一些写着dsslogo但是其实是鲁班的
还有dss/module/footer/guide下面有很多带着鲁班的logo的截图 看看是重新截还是直接裁剪一下？

---
还有这里
https://github.com/kingsGlory/DataSphereStudio/blob/e2b6bd72c66583bdb52089f62638fbd390f50146/web/src/apps/dataGovernance/view/assetsInfo/components/lineage/symbol/demo_index.html#L13
和这里https://github.com/kingsGlory/DataSphereStudio/blob/e2b6bd72c66583bdb52089f62638fbd390f50146/web/src/dss/assets/DSFont/demo_index.html#L13
这里两个资源是啥情况 看起来像是私有的对象存储？

2021-12-29 02:03 UTC, det101 commented
> @det101
> 
> 可以麻烦把鲁班/鲁蛋相关的文字和图片替换/删除掉吗 比如dss/assets/images/下面有一些写着dsslogo但是其实是鲁班的 还有dss/module/footer/guide下面有很多带着鲁班的logo的截图 看看是重新截还是直接裁剪一下？
> 
> 还有这里 https://github.com/kingsGlory/DataSphereStudio/blob/e2b6bd72c66583bdb52089f62638fbd390f50146/web/src/apps/dataGovernance/view/assetsInfo/components/lineage/symbol/demo_index.html#L13 和这里https://github.com/kingsGlory/DataSphereStudio/blob/e2b6bd72c66583bdb52089f62638fbd390f50146/web/src/dss/assets/DSFont/demo_index.html#L13 这里两个资源是啥情况 看起来像是私有的对象存储？


鲁班logo我已经换了, 文档截图这块内容比较多，最后统一改，现在文档这块正在改版做成可编辑的

2022-02-24 08:29 UTC, closed without merging